development:
  adapter: async

test:
  adapter: test

production:
  adapter: redis
  url: <%= ENV["REDISCLOUD_URL"].present? ? URI.parse(ENV["REDISCLOUD_URL"]) : "redis://localhost:6379/1" %>
  channel_prefix: sample_app_production
