development:
  adapter: async

test:
  adapter: test

production:
  adapter: redis
  url: <%= ENV.fetch("REDISCLOUD_URL") { URI.parse(ENV["REDISCLOUD_URL"]) } %>
  channel_prefix: sample_app_production
